### ISSUE TITLE
How to use this library

### ISSUE THREAD

**Issue by spernica** [RonasIT/laravel-ics-generator#1]
How to create something with this library?

**Comment by Asxer** [comment]
@spernica It registers a router in the project, using which you can get the generated ics file. You can specify route path in configs. Client side can get ics-files though call of this route with parameters which described here https://github.com/RonasIT/laravel-ics-generator#parameters-of-request

**Comment by piep14** [comment]
I dont understand how to generate a ICS file. Can you help me ?

Thank

**Comment by Asxer** [comment]
@piep14 I've added How to use block to documentation. Could you please check it?
